/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.funcionarios.iud.app.test;

import com.mycompany.funcionarios.iud.app.controller.FuncionarioController;
import com.mycompany.funcionarios.iud.app.domain.Funcionario;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yefer
 */
public class Main2 extends javax.swing.JFrame {

    private final FuncionarioController funcionarioController;
    private final static String[] COLUMNS = {"ID", "T.DOCUMENTOS", "N.DOCUMENTO", "NOMBRE", "APELLIDO", "ESTADO CIVIL", "SEXO", "DIRECCION", "TELEFONO", "F.NACIMIENTO"};
    private final static String SELECCION = "--SELECCIONE--";

    /**
     * Creates new form Main2
     */
    public Main2() {
        initComponents();
        txtFuncionarioId.setEditable(false);
        funcionarioController = new FuncionarioController();
        listFuncionarios();
        addListener();

    }

    private void listFuncionarios() {
        cbxfuncionarios.removeAllItems();
        Funcionario funcionario1 = new Funcionario();
        funcionario1.setNombre(SELECCION);
        funcionario1.setApellido("");
        cbxfuncionarios.addItem(funcionario1);
        tblFuncionario.removeAll();
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        for (String COLUMN : COLUMNS) {
            defaultTableModel.addColumn(COLUMN);
        }

        tblFuncionario.setModel(defaultTableModel);

        try {
            List<Funcionario> funcionarios = funcionarioController.obtenerFun();
            if (funcionarios.isEmpty()) {
                return;
            }
            defaultTableModel.setRowCount(funcionarios.size());
            int row = 0;
            for (Funcionario funcionario : funcionarios) {
                defaultTableModel.setValueAt(funcionario.getId(), row, 0);
                defaultTableModel.setValueAt(funcionario.getTipo_doccumento(), row, 1);
                defaultTableModel.setValueAt(funcionario.getNumero_documento(), row, 2);
                defaultTableModel.setValueAt(funcionario.getNombre(), row, 3);
                defaultTableModel.setValueAt(funcionario.getApellido(), row, 4);
                defaultTableModel.setValueAt(funcionario.getEstado_civil(), row, 5);
                defaultTableModel.setValueAt(funcionario.getSexo(), row, 6);
                defaultTableModel.setValueAt(funcionario.getDireccion(), row, 7);
                defaultTableModel.setValueAt(funcionario.getTelefono(), row, 8);
                defaultTableModel.setValueAt(funcionario.getFecha_nacimiento(), row, 9);
                row++;

                cbxfuncionarios.addItem(funcionario);

            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void addListener() {
        cbxfuncionarios.addItemListener(event -> {
            Funcionario selectedFuncionario = (Funcionario) event.getItem();
            if (selectedFuncionario.getNombre().equals(SELECCION)) {
                txtFuncionarioId.setText("");
                txtEdiTDoc.setText("");
                txtEdiNDoc.setText("");
                txtEdiNombre.setText("");
                txtEdiApellido.setText("");
                txtEdiECivil.setText("");
                txtEdiSexo.setText("");
                txtEdiDireccion.setText("");
                txtEdiTelefono.setText("");
                txtEdiFNacimiento.setText("");

            } else {
                txtFuncionarioId.setText(String.valueOf(selectedFuncionario.getId()));
                txtEdiTDoc.setText(selectedFuncionario.getTipo_doccumento());
                txtEdiNDoc.setText(selectedFuncionario.getNumero_documento());
                txtEdiNombre.setText(selectedFuncionario.getNombre());
                txtEdiApellido.setText(selectedFuncionario.getApellido());
                txtEdiECivil.setText(selectedFuncionario.getEstado_civil());
                txtEdiSexo.setText(selectedFuncionario.getSexo());
                txtEdiDireccion.setText(selectedFuncionario.getDireccion());
                txtEdiTelefono.setText(selectedFuncionario.getTelefono());
                txtEdiFNacimiento.setText(selectedFuncionario.getFecha_nacimiento());

            }
            System.out.println("selectedFuncionario = " + selectedFuncionario);

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTPane = new javax.swing.JTabbedPane();
        jPCrear = new javax.swing.JPanel();
        jPCampos1 = new javax.swing.JPanel();
        lblDocumento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNDocumento = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblEstadoCivil = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtEstadoCivil = new javax.swing.JTextField();
        txtNDocumento = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTDocumento = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        jPEditar = new javax.swing.JPanel();
        jPCampos = new javax.swing.JPanel();
        lblnombre = new javax.swing.JLabel();
        lblNDoc = new javax.swing.JLabel();
        lblEstadoCiv = new javax.swing.JLabel();
        lblApellid = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblDirecci = new javax.swing.JLabel();
        lblNaci = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        lblTDocumento = new javax.swing.JLabel();
        cbxfuncionarios = new javax.swing.JComboBox<>();
        lblFuncionariId = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFuncionarioId = new javax.swing.JTextField();
        txtEdiTDoc = new javax.swing.JTextField();
        txtEdiNDoc = new javax.swing.JTextField();
        txtEdiNombre = new javax.swing.JTextField();
        txtEdiApellido = new javax.swing.JTextField();
        txtEdiECivil = new javax.swing.JTextField();
        txtEdiSexo = new javax.swing.JTextField();
        txtEdiDireccion = new javax.swing.JTextField();
        txtEdiTelefono = new javax.swing.JTextField();
        txtEdiFNacimiento = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("GESTION DE FUNCIONARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 210, -1));

        jPCampos1.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite los siguentes campos"));

        lblDocumento.setText("T.DOCUMENTOS");

        lblNDocumento.setText("N.DOCUMENTO");

        lblNombre.setText("NOMBRE");

        lblApellido.setText("APELLIDO");

        lblEstadoCivil.setText("ESTADO CIVIL");

        lblSexo.setText("SEXO");

        lblTelefono.setText("TELEFONO");

        lblDireccion.setText("DIRECCION");

        lblFechaNacimiento.setText("F.NACIMIENTO");

        txtFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoActionPerformed(evt);
            }
        });

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });

        txtEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoCivilActionPerformed(evt);
            }
        });

        txtNDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNDocumentoActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        txtTDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTDocumentoActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCampos1Layout = new javax.swing.GroupLayout(jPCampos1);
        jPCampos1.setLayout(jPCampos1Layout);
        jPCampos1Layout.setHorizontalGroup(
            jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCampos1Layout.createSequentialGroup()
                .addGroup(jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCampos1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCampos1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtTDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPCampos1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtNDocumento)))
                        .addGap(18, 18, 18)
                        .addGroup(jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCampos1Layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellido)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCampos1Layout.createSequentialGroup()
                                .addComponent(lblEstadoCivil)
                                .addGap(18, 18, 18)
                                .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPCampos1Layout.createSequentialGroup()
                                .addComponent(txtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccion)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefono)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPCampos1Layout.createSequentialGroup()
                        .addGap(494, 494, 494)
                        .addComponent(btnCrear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPCampos1Layout.setVerticalGroup(
            jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCampos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFechaNacimiento)
                        .addComponent(lblTelefono)
                        .addComponent(lblDireccion)
                        .addComponent(lblSexo)
                        .addComponent(lblEstadoCivil)
                        .addComponent(lblApellido)
                        .addComponent(lblNombre)
                        .addComponent(lblNDocumento)
                        .addComponent(lblDocumento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(btnCrear))
        );

        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblFuncionario);

        javax.swing.GroupLayout jPCrearLayout = new javax.swing.GroupLayout(jPCrear);
        jPCrear.setLayout(jPCrearLayout);
        jPCrearLayout.setHorizontalGroup(
            jPCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCrearLayout.createSequentialGroup()
                .addComponent(jPCampos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(jPCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPCrearLayout.setVerticalGroup(
            jPCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCrearLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPCampos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTPane.addTab("Crear funcionario", jPCrear);

        jPCampos.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifique los siguientes campos "));

        lblnombre.setText("NOMBRE");

        lblNDoc.setText("N.DOCUMENTO");

        lblEstadoCiv.setText("ESTADO CIVIL");

        lblApellid.setText("APELLIDO");

        lblSex.setText("SEXO");

        lblDirecci.setText("DIRECCION");

        lblNaci.setText("F.NACIMIENTO");

        lblTel.setText("TELEFONO");

        lblTDocumento.setText("T.DOCUMENTOS");

        cbxfuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxfuncionariosActionPerformed(evt);
            }
        });

        lblFuncionariId.setText("ID");

        jLabel12.setText("Funcionarios");

        txtFuncionarioId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncionarioIdActionPerformed(evt);
            }
        });

        txtEdiTDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdiTDocActionPerformed(evt);
            }
        });

        txtEdiDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdiDireccionActionPerformed(evt);
            }
        });

        txtEdiTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdiTelefonoActionPerformed(evt);
            }
        });

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCamposLayout = new javax.swing.GroupLayout(jPCampos);
        jPCampos.setLayout(jPCamposLayout);
        jPCamposLayout.setHorizontalGroup(
            jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCamposLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(btnActualizar)
                .addGap(97, 97, 97)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPCamposLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCamposLayout.createSequentialGroup()
                        .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCamposLayout.createSequentialGroup()
                                .addComponent(txtFuncionarioId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEdiTDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPCamposLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblFuncionariId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxfuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCamposLayout.createSequentialGroup()
                                .addComponent(lblNDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lblApellid))
                            .addGroup(jPCamposLayout.createSequentialGroup()
                                .addComponent(txtEdiNDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEdiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEdiApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCamposLayout.createSequentialGroup()
                                .addComponent(txtEdiECivil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPCamposLayout.createSequentialGroup()
                                .addComponent(lblEstadoCiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(52, 52, 52)))
                        .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdiSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSex, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDirecci, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdiDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdiTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdiFNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addComponent(jLabel12)))
        );
        jPCamposLayout.setVerticalGroup(
            jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCamposLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxfuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionariId)
                    .addComponent(lblTDocumento)
                    .addComponent(lblNDoc)
                    .addComponent(lblnombre)
                    .addComponent(lblApellid)
                    .addComponent(lblSex)
                    .addComponent(lblDirecci)
                    .addComponent(lblTel)
                    .addComponent(lblNaci)
                    .addComponent(lblEstadoCiv))
                .addGap(18, 18, 18)
                .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFuncionarioId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdiTDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdiNDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdiApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdiECivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdiSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdiDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdiTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdiFNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPEditarLayout = new javax.swing.GroupLayout(jPEditar);
        jPEditar.setLayout(jPEditarLayout);
        jPEditarLayout.setHorizontalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPEditarLayout.setVerticalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        jTPane.addTab("Editar funcionario", jPEditar);

        getContentPane().add(jTPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1070, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed

    private void txtEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoCivilActionPerformed

    private void txtNDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNDocumentoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtTDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTDocumentoActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        if (txtTDocumento.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite El tipo de documento");
            txtTDocumento.requestFocus();
            return;
        }

        if (txtNDocumento.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite El Numero de documento");
            txtNDocumento.requestFocus();
            return;
        }

        if (txtNombre.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el Nombre");
            txtNombre.requestFocus();
            return;
        }

        if (txtApellido.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el apellido");
            txtApellido.requestFocus();
            return;
        }

        if (txtEstadoCivil.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el estado civil");
            txtEstadoCivil.requestFocus();
            return;
        }

        if (txtSexo.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el sexo");
            txtSexo.requestFocus();
            return;
        }

        if (txtDireccion.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite la direccion");
            txtDireccion.requestFocus();
            return;
        }

        if (txtTelefono.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Nombre");
            txtTelefono.requestFocus();
            return;
        }

        if (txtFechaNacimiento.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite la fecha de nacimiento");
            txtFechaNacimiento.requestFocus();
            return;
        }

        try {
            Funcionario funcionario = new Funcionario();
            funcionario.setTipo_doccumento(txtTDocumento.getText().trim());
            funcionario.setNumero_documento(txtNDocumento.getText().trim());
            funcionario.setNombre(txtNombre.getText().trim());
            funcionario.setApellido(txtApellido.getText().trim());
            funcionario.setEstado_civil(txtEstadoCivil.getText().trim());
            funcionario.setSexo(txtSexo.getText().trim());
            funcionario.setDireccion(txtDireccion.getText().trim());
            funcionario.setTelefono(txtTelefono.getText().trim());
            funcionario.setFecha_nacimiento(txtFechaNacimiento.getText().trim());

            funcionarioController.crear(funcionario);
            txtTDocumento.setText("");
            txtNDocumento.setText("");
            txtNombre.setText("");
            txtApellido.setText("");
            txtEstadoCivil.setText("");
            txtSexo.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            txtFechaNacimiento.setText("");
            listFuncionarios();
            JOptionPane.showMessageDialog(null, "Funcionario creado con exito");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "No se pudo crear el carro");

        }


    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtFuncionarioIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncionarioIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncionarioIdActionPerformed

    private void txtEdiTDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdiTDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdiTDocActionPerformed

    private void txtEdiDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdiDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdiDireccionActionPerformed

    private void txtEdiTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdiTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdiTelefonoActionPerformed

    private void cbxfuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxfuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxfuncionariosActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        if (txtFuncionarioId.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite El id");
            txtFuncionarioId.requestFocus();
            return;
        }

        if (txtEdiTDoc.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite El tipo de documento");
            txtEdiTDoc.requestFocus();
            return;
        }

        if (txtEdiNDoc.getText().trim().length() == 0) {
            JOptionPane.showConfirmDialog(null, "Digite El Numero de documento");
            txtEdiNDoc.requestFocus();
            return;
        }

        if (txtEdiNombre.getText().trim().length() == 0) {
            JOptionPane.showConfirmDialog(null, "Digite el Nombre");
            txtEdiNombre.requestFocus();
            return;
        }

        if (txtEdiApellido.getText().trim().length() == 0) {
            JOptionPane.showConfirmDialog(null, "Digite el apellido");
            txtEdiApellido.requestFocus();
            return;
        }

        if (txtEdiECivil.getText().trim().length() == 0) {
            JOptionPane.showConfirmDialog(null, "Digite el estado civil");
            txtEdiECivil.requestFocus();
            return;
        }

        if (txtEdiSexo.getText().trim().length() == 0) {
            JOptionPane.showConfirmDialog(null, "Digite el sexo");
            txtEdiSexo.requestFocus();
            return;
        }

        if (txtEdiDireccion.getText().trim().length() == 0) {
            JOptionPane.showConfirmDialog(null, "Digite la direccion");
            txtEdiDireccion.requestFocus();
            return;
        }

        if (txtEdiTelefono.getText().trim().length() == 0) {
            JOptionPane.showConfirmDialog(null, "Digite Nombre");
            txtEdiTelefono.requestFocus();
            return;
        }

        if (txtEdiFNacimiento.getText().trim().length() == 0) {
            JOptionPane.showConfirmDialog(null, "Digite la fecha de nacimiento");
            txtEdiFNacimiento.requestFocus();
            return;
        }

        Funcionario funcionario = new Funcionario();
        funcionario.setTipo_doccumento(txtEdiTDoc.getText().trim());
        funcionario.setNumero_documento(txtEdiNDoc.getText().trim());
        funcionario.setNombre(txtEdiNombre.getText().trim());
        funcionario.setApellido(txtEdiApellido.getText().trim());
        funcionario.setEstado_civil(txtEdiECivil.getText().trim());
        funcionario.setSexo(txtEdiSexo.getText().trim());
        funcionario.setDireccion(txtEdiDireccion.getText().trim());
        funcionario.setTelefono(txtEdiTelefono.getText().trim());
        funcionario.setFecha_nacimiento(txtEdiFNacimiento.getText().trim());

        int opt = JOptionPane.showConfirmDialog(null, "Desea actualizar el funcionario",
                "Confirmar salida", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (opt == 0) {

            try {
                funcionarioController.actualizarFun(Integer.parseInt(txtFuncionarioId.getText()), funcionario);
                txtFuncionarioId.setText("");
                txtEdiTDoc.setText("");
                txtEdiNDoc.setText("");
                txtEdiNombre.setText("");
                txtEdiApellido.setText("");
                txtEdiECivil.setText("");
                txtEdiSexo.setText("");
                txtEdiDireccion.setText("");
                txtEdiTelefono.setText("");
                txtEdiFNacimiento.setText("");
                listFuncionarios();
                JOptionPane.showMessageDialog(null, "Se ha actualizado el carro correctamente");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No fue posible actualizar el funcionario");
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (txtFuncionarioId.getText().trim().length() == 0) {
            JOptionPane.showConfirmDialog(null, "seleccione un funcionario ");
            txtFuncionarioId.requestFocus();
            return;
        }
         int opt = JOptionPane.showConfirmDialog(null, "Desea actualizar el eliminar el funcionarioo", 
                "Confirmar salida ", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        
        if (opt == 0) {
            
            try {
                funcionarioController.eliminarFun(Integer.parseInt(txtFuncionarioId.getText()));
                txtFuncionarioId.setText("");
                txtEdiNDoc.setText("");
                txtEdiTDoc.setText("");                
                txtEdiNombre.setText("");
                txtEdiApellido.setText("");
                txtEdiECivil.setText("");
                txtEdiSexo.setText("");
                txtEdiDireccion.setText("");
                txtEdiTelefono.setText("");
                txtEdiFNacimiento.setText("");               
                listFuncionarios();
                JOptionPane.showMessageDialog(null,"Se ha actualizado el funcionario correctamente");
                
                                 
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"No fue posible eliminar el funcionario");
            ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<Funcionario> cbxfuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPCampos;
    private javax.swing.JPanel jPCampos1;
    private javax.swing.JPanel jPCrear;
    private javax.swing.JPanel jPEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTPane;
    private javax.swing.JLabel lblApellid;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblDirecci;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblEstadoCiv;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblFuncionariId;
    private javax.swing.JLabel lblNDoc;
    private javax.swing.JLabel lblNDocumento;
    private javax.swing.JLabel lblNaci;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTDocumento;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTable tblFuncionario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdiApellido;
    private javax.swing.JTextField txtEdiDireccion;
    private javax.swing.JTextField txtEdiECivil;
    private javax.swing.JTextField txtEdiFNacimiento;
    private javax.swing.JTextField txtEdiNDoc;
    private javax.swing.JTextField txtEdiNombre;
    private javax.swing.JTextField txtEdiSexo;
    private javax.swing.JTextField txtEdiTDoc;
    private javax.swing.JTextField txtEdiTelefono;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtFuncionarioId;
    private javax.swing.JTextField txtNDocumento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTDocumento;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
